author: Tjs238
database: true
description: Let users protect their own land with potion protect!
main: me.tjs238.plugins.potionprotect.Potionprotect
name: PotionProtect
url: http://diamondcraft.co/
version: '1.3'
depends: [WorldGuard, WorldEdit]
softdepends: [Vault]
commands:
  groupset:
    description: Set the ranks of donors
    usage: /groupset <player> <group> [world]
    aliases: gs